"Resource/UI/HUD_Base.res"
{
	"HudKillCamEventPanel"
	{
		"ControlName"			"EditablePanel"
		"fieldName"			"HudKillCamEventPanel"
		"wide"				"243"
		"tall"				"28"
		"zpos"				"5"
		"autoResize"			"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"textAlignment"			"west"
		"dulltext"			"0"
		"brighttext"			"1"
		"bgcolor_override"		"0 0 0 255"
		"fgcolor_override"		"0 0 0 255"
		"PaintBackgroundType"			"2"
	}

	"HudKillCamEventPanelBackground"
	{
		"ControlName"				"EditablePanel"
		"fieldName"				"HudKillCamEventPanelBackground"
		"xpos"					"0"
		"ypos"					"0"
		"wide"					"220"
		"tall"					"25"
		"zpos"					"6"
		"autoResize"				"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"textAlignment"				"west"
		"dulltext"				"0"
		"brighttext"				"1"
		"bgcolor_override"			"0 0 0 255"
		"fgcolor_override"			"0 0 0 255"
		"PaintBackgroundType"			"2"
	}
	

	"EventDescription"
	{
		"ControlName"			"RichText"
		"fieldName"			"EventDescription"
		"xpos"				"4"
		"ypos"				"0"
		"zpos"				"7"
		"wide"				"220"
		"tall"				"12"
		"enabled"			"1"
		"scaleImage"			"1"
		"visible"			"1"
		"textAlignment"			"north-west"
		"wrap"				"1"
		"scrollbar"			"false"
		"text"				""
		"font" 				"Times12Thick"
		"fgColor_override" 		"150 150 150 255"
		"bgcolor_override"		"0 0 0 0"
		"auto_wide_tocontents"		"0"
		"auto_tall_tocontents"	"1"
	}

	"KillCamElementFooter"
	{
		"ControlName"				"EditablePanel"
		"fieldName"				"KillCamElementFooter"
		"xpos"					"8"
		"ypos"					"20"
		"wide"					"220"
		"tall"					"2"
		"zpos"					"7"
		"autoResize"				"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"textAlignment"				"west"
		"dulltext"				"0"
		"brighttext"				"1"
		"bgcolor_override"			"75 75 75 255"
		"fgcolor_override"			"0 0 0 255"
		"PaintBackgroundType"			"2"
	}


}
